### ISSUE TITLE
Smite Recommendations

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#108]
I spoke to the current Smite manager, Xlenna, and she had some really good recommendations for the website. 

I'm going to do these in bullet points and there will need to be a PR for each point. Just mention this issue in all of the PRs.

- Player bio on card. I just straight up forgot to include this. Use conditional rendering if the player has a bio and a `<Card.Text>` containing the bio.
- Edit the current "Save Team" button and create a new "Confirm Save" button using a hook variable. Look at how I did `confirmDelete` to do sorta the same thing.
- Add a reset / confirm reset button. Just store the initial team after it's loaded into another `useState()` hook and use some logic when the confirm reset button to set the team to the old, saved one. Look inside of the `useEffect()` hook to how I save the team. create a `confirmReset` hook variable just like `confirmSave`.

For the last 2 bullet points, because those are in the team-edit component and not the team-form we can render just one button using a ternary and not 2 like the delete button.
(i.g. `{ confirmSave ? <Confirm Save Button> : <Save Button> }` (same with reset). 
These buttons should be at the top of the edit page and one on top of the other as to not be anywhere near the delete button.  

I believe this will clean things up. Still use the outline of a button for the "confirm" version. I like the color scheme of 
- Save - Green ( Success )
- Reset - Yellow ( Warning )
- Delete - Red ( Danger )

**Comment by evanextreme** [comment]
Can we rename this issue or split it into multiple tickets?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NeilBeforeMemes** [comment]
This definitely should be split
