### ISSUE TITLE
Add Style Guide

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#116]
For most of the code I had been going off a personal style guide that only I knew and never wrote down. I propose we move to a more standard guide that way everyone can write the same clean code. 

Some style guides to look at
- Airbnb [JS](https://github.com/airbnb/javascript) / [React](https://github.com/airbnb/javascript/tree/master/react) / [CSS](https://github.com/airbnb/css)
- [Google](https://google.github.io/styleguide/jsguide.html)
- [JavaScript Standard Style](https://github.com/standard/standard)

Now, my personal opinion is to go with Airbnb. With `tslint` and `eslint` merging, I believe that having all ts/tsx/scss under one guide is ideal.

**Comment by evanextreme** [comment]
whatever guide we use, we should set up CI linting to check PR's for style

**Comment by rag4214** [comment]
We have decided to go with Airbnb's style guide.

Moving all of the rules to react and typescript will take time but this is the highest priority issue from here on.

**Comment by rag4214** [comment]
Closed in #142
