### ISSUE TITLE
Embed "Meet the Team" Videos if Provided

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#138]
This one requires both the front end and backed to be updated, maybe something like a `videoUrl`/`videoUrls`? property on a team schema that links to a "Meet the Team" video on the [RIT Esports Youtube Channel](https://www.youtube.com/channel/UCswSm4rb9NJCQC02vjAYRvQ?reload=9).

We can go with `videoUrl: string` to the most updated video or `videoUrls: string[]` that can link to each iteration of the Meet the Team videos.

These will then be conditionally embedded in each team's page (maybe in a [React-Bootstrap Carousel](https://react-bootstrap.github.io/components/carousel/)?)

**Comment by evanextreme** [comment]
Duplicate of #40

**Comment by rag4214** [comment]
Good catch! Thank you
