### ISSUE TITLE
Twitch Stream Embed on Homepage If Live

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#140]
We should use Twitch's [embed everything](https://dev.twitch.tv/docs/embed/everything) to embed the [RITEsports twitch channel](https://www.twitch.tv/ritesports) on the homepage.

I want to complicate this and only embed the stream if it is live. 
We can do this a purely front-end way, or do some caching on our back end and have a route. This will cut down on Twitch API requests, but will require more work from us.

**Comment by evanextreme** [comment]
@rag4214 this is a duplicate of #48

**Comment by rag4214** [comment]
Good catch, thank you!
