### ISSUE TITLE
Utilize Esportspedia API

### ISSUE THREAD

**Issue by zSmgl** [RITesports/Website#143]
The current website exists where information about past victories, rosters, etc is stored: https://www.esportspedia.com/collegiate/Rochester_Institute_of_Technology

1 of 2 things come to mind regarding the site...

A) Implementing our own version of this with log in features for managers to use on the website.
This could be - specifically - a page for "2019-2020 Fall Achievements" Where managers can add how their respective teas did. And then including "2019-2020 rosters" Although, this all seems be too much...

B) My personal recommendation: Create a "History" Page in some way (well thought out, ask for input on what should / shouldn't go on this page) with multiple tabs that link to various things like achievements, rosters, etc that can be updated on a yearly or semester basis. My personal vision is this page divided into "Recent Achievements" and "Historical Achievements" where things may be customize, with a 3rd link going to the esportspedia site.

Anytime rosters change on the site between a given timezone (say every 1 month), the esportspedia rosters can be automatically updated. Previous iterations of Rosters save somewhere on the wiki site, too, as a functionality. Additionally, tracking how ALL Teams do should be key. Good or bad, the wiki can become a place of historically looking back and seeing every team's history. 

A Link to the API can be found here: https://www.mediawiki.org/wiki/API. This will likely be another major update, but is best to roadmap now.

**Comment by evanextreme** [comment]
I think this API is much better suited for third party applications than our own site's use, and we could keep both as separate components, especially since this information is updated infrequently
