### ISSUE TITLE
Create and Configure CDN

### ISSUE THREAD

**Issue by NeilBeforeMemes** [RITesports/website#36]
A CDN will be necessary for images used for games, players, etc. on the site.

This will require research on how to use and configure a CDN in our current environment (via a automatically configured DigitalOcean service or a Linux service that we will need to configure ourselves)

**Comment by evanextreme** [comment]
billing is up and running. Right now NYC3 seems to be down for a while, but lets just use SF2 and work off there. Lets try to get images up and running before Friday if we can @NeilBeforeMemes, would love to launch then.

**Comment by NeilBeforeMemes** [comment]
Done!
