### ISSUE TITLE
Live on Twitch

### ISSUE THREAD

**Issue by evanextreme** [RITesports/Website#48]
We can build a system that checks if one of our teams is live on Twitch and if so, display that stream live on the homepage of our website. It would check to see if the RITesports channel is live first, and show that if it is. Otherwise, it would look at the following channels to see if they are live _and_ if RIT (or any variation of it) is in the stream title, showing those instead.

- cstarleague
- cstarleague2
- avgl
- collegiater6
- collegiatepubg
- collegecarball
- blizzheroes
- playhearthstone
- and more that I am forgetting

I suggest @rag4214 builds a function which returns a list matching this and @NeilBeforeMemes implements it in the frontend. Possibly showing the "highest priority" stream on our homepage, and possibly creating a new "live" page.

**Comment by rag4214** [comment]
Updating from closed duplicate

We should use Twitch's [embed everything](https://dev.twitch.tv/docs/embed/everything) to embed the RITEsports [twitch channel](https://www.twitch.tv/ritesports) on the homepage.

We can do this a purely front-end way, or do some caching on our back end and have a route. This will cut down on Twitch API requests, but will require more work from us.
