### ISSUE TITLE
Hover effect on team cards

### ISSUE THREAD

**Issue by Gladdstone** [RITesports/website#49]
Team cards should react to mouse scroll-over. This should be a CSS shaking animation, and if possible, the addition of full color to the logo. JavaScript used in this ticket should be limited or none.

https://esportsrit.com/teams

**Comment by jlutin** [comment]
Hello, I am interested in contributing to this project. can I take this issue?

**Comment by evanextreme** [comment]
@jlutin sure thing! Submit a PR and @Gladdstone will take a look

**Comment by jlutin** [comment]
@evanextreme I have succeeded to run app on my local, however my mongodb is empty, so /teams url shows no page. can you please share with me sample db migration?
