### ISSUE TITLE
Combine Team Components

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#78]
This is a very large task and I will 100% help whoever I assign to this. 

Currently in our team folder many of the components can be combined into one depending on the `@Input` bindings given. I propose we combine all the `new` and `edit` components into their base component.

| Team | Division | Player |
| --- | --- | --- |
| team-list | division-details | player-card |
| team-details | division-details-edit | player-card-edit |
| team-details-edit | | new-player-card |
| team-details-new|
| team-card |

can be combined into

| Team | Division | Player |
| --- | --- | --- |
| team-list | division-details | player-card |
| team-details |
| team-card |

If we *really* want to go super abstract, we can combine everything down even further into

| Card | Details | List |
| --- | --- | --- |

But I feel that will become too abstract.

Opinions are wanted before assignment.

**Comment by rag4214** [comment]
Going to @Gladdstone @NeilBeforeMemes and @evanextreme to see what they think about this.

**Comment by Gladdstone** [comment]
Look into state management with Redux.

**Comment by rag4214** [comment]
closed in #83
