### ISSUE TITLE
Cross Env Support

### ISSUE THREAD

**Issue by rag4214** [RITesports/website#85]
I realized the react start script is different between Windows and Linux builds. 

Currently the start script for development is
```
"start": "PORT=4200 react-scripts start",
```
which works on Linux.

Most of our team devs on windows and needs to change it to
```
"start": "set PORT=4200 && react-scripts start",
```

I propose for cross platform support we install [cross-env](https://www.npmjs.com/package/cross-env#installation) via npm and change the `react-app/package.json` start script for development to be
```
"start": "cross-env PORT=4200 react-scripts start",
```

**Comment by NeilBeforeMemes** [comment]
It's usually a good idea to make your environment variable names more unique. Many applications just use a prefix before all their environment variables. Something like RITESPORTS_PORT or ESPORTS_PORT might be better.

**Comment by rag4214** [comment]
`react-scripts` uses the `PORT` env variable to start it's web server (which I don't believe we can change unless we eject). However (correct me if I'm wrong), by setting it in the `npm start` script itself that should not effect any other `PORT` env variables because it's not technically being saved by the terminal.

**Comment by rag4214** [comment]
Done with #89
